project:
  type: book
  output-dir: "validation-notebook"
  
book:
  title: "Dayim Estimation Results"
  repo-url: https://github.com/psrc/soundcast/tree/base_year_2023/scripts/summarize/validation
  search: false
  sidebar:
    logo: PSRClogo2016path.png

  chapters:
    - index.qmd
    - validation_scripts/telecommute.ipynb
    - validation_scripts/auto_ownership.ipynb
    - validation_scripts/transit_pass_ownership.ipynb
    - validation_scripts/day_pattern.ipynb
    - validation_scripts/intermediate_stop_generation.ipynb
    - validation_scripts/workbased_subtour_generation.ipynb
    - validation_scripts/time_choice.ipynb
    - part: "<b>LOCATION CHOICE</b>"
      chapters:
        - validation_scripts/work_location.ipynb
        - validation_scripts/school_location.ipynb
    - part: "<b>TOUR MODE CHOICE</b>"
      chapters:
        - validation_scripts/all_tour_mode.ipynb
        - validation_scripts/work_tour_mode.ipynb
        - validation_scripts/school_tour_mode.ipynb
        - validation_scripts/escort_tour_mode.ipynb
        - validation_scripts/other_home_based_tour_mode.ipynb
        - validation_scripts/workbased_subtour_mode.ipynb
    - part: "<b>TRIP MODE CHOICE</b>"
      chapters:
        - validation_scripts/all_trip_mode.ipynb
        - validation_scripts/work_trip_mode.ipynb   
        - validation_scripts/school_trip_mode.ipynb   
        - validation_scripts/escort_trip_mode.ipynb   
        - validation_scripts/other_home_based_trip_mode.ipynb       
    - part: "<b>DESTINATION CHOICE</b>"
      chapters:
        - validation_scripts/tour_destination.ipynb
        - validation_scripts/trip_destination.ipynb
    - part: "<b>REGIONAL SUMMARY</b>"
      chapters:
        - validation_scripts/persons.ipynb
        - validation_scripts/households.ipynb
        - validation_scripts/tours.ipynb
        - validation_scripts/trips.ipynb
    - part: "<b>ANALYSIS</b>"
      chapters:
        - validation_scripts/telecommute_analysis.ipynb

format:
  html:
    mainfont: Poppins
    theme: 
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    echo: false
    code-tools: true

toc: true




