project:
  type: book
  output-dir: "validation-notebook"
  
book:
  title: "<br>Dayim Estimation Results"
  repo-url: https://github.com/psrc/travel-modeling/tree/master/estimation
  search: false
  sidebar:
    logo: PSRClogo2016path.png

  chapters:
    - index.qmd
    - validation_scripts/telecommute.ipynb
    - validation_scripts/auto_ownership.ipynb
    - validation_scripts/transit_pass_ownership.ipynb
    - validation_scripts/day_pattern.ipynb
    - part: "<b>LOCATION CHOICE</b>"
      chapters:
        - validation_scripts/work_location.ipynb
        - validation_scripts/school_location.ipynb
    - part: "<b>TOUR MODE CHOICE</b>"
      chapters:
        - validation_scripts/work_tour_mode.ipynb
        - validation_scripts/school_tour_mode.ipynb
        - validation_scripts/escort_tour_mode.ipynb
        - validation_scripts/other_home_based_tour_mode.ipynb
    - part: "<b>DESTINATION CHOICE</b>"
      chapters:
        - validation_scripts/tour_destination.ipynb
        - validation_scripts/trip_destination.ipynb
    - part: "<b>REGIONAL SUMMARY</b>"
      chapters:
        - validation_scripts/persons.ipynb
        - validation_scripts/households.ipynb

format:
  html:
    mainfont: Poppins
    theme: 
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    echo: false
    code-tools: true

toc: true




