################################################################
# Validation input files and output directory names
################################################################


# model results
# ---- local soundcast run
model_dir = '../../../..'
# ---- (JL: for summary development)
#model_dir = "//modelstation2/c$/Workspace/sc_2023_all_day_transit_6_11_24"

# ---- survey results
# 2023
survey_dir = "R:/e2projects_two/2023_base_year/2023_survey/daysim_format/cleaned/skims_attached/uncloned"
tour_survey_dir = "R:/e2projects_two/2023_base_year/2023_survey/daysim_format/cleaned/skims_attached"
# 2017/2019
include_2017_2019 = true
survey_2017_dir = "R:/e2projects_two/2023_base_year/2017_2019_survey/test/cleaned/skims_attached/uncloned"
tour_survey_2017_dir = "R:/e2projects_two/2023_base_year/2017_2019_survey/test/cleaned/skims_attached"

# other validation dataset
p_acs_auto_ownership = "R:/e2projects_two/activitysim/estimation/2017_2019_data/validation_data/auto_ownership/bg_auto_ownership.csv"
p_maz_bg_lookup =      "R:/e2projects_two/activitysim/estimation/2017_2019_data/validation_data/auto_ownership/maz_bg_lookup.csv"

# validation output directory
p_output_dir = "outputs/2023_validation"

################################################################
# run validation notebooks
################################################################
network_summary_list = ['transit_validation',
                        'traffic_validation']
#network_summary_list = ['traffic_validation']
summary_list = ['work_location',
                'transit_pass_ownership',
                'school_location',
                'auto_ownership',
                'work_tour_mode',
                'school_tour_mode',
                'escort_tour_mode',
                'telecommute',
                'other_home_based_tour_mode',
                'tour_destination',
                'trip_destination',
                'day_pattern',
                'persons',
                'households',
                'tours']
#summary_list = ['auto_ownership']

# color palatte for plots
psrc_color = ["#91268F", "#8CC63E", "#00A7A0", "#F05A28", "#4C4C4C", "#630460", "#9f3913", "#588527", "#00716c", "#3e4040"]